import { describe, expect, it } from 'vitest'
import * as shared from './index'
// 纯类型：通过 import type 引用，编译期验证存在（运行时被类型擦除）
import type {
    Jwk,
    RsaAlgorithm,
    AesAlgorithm,
    EpochMs,
    ValidationResult,
    Batch,
    BatchStatus,
    CalcMode,
    RankScope,
    CalcConfig,
    UnitConfig,
    UnitConfigStatus,
    UnitType,
    UnitBinding,
    CascaderNode,
    ClassCascader,
    StudentField,
    ScoreType,
    ScoreTypeStepper,
    ScoreTypeRadio,
    ScoreTypeInput,
    Support,
    DyfConfig,
    DyfCategory,
    DyfGroup,
    DyfItem,
    UnitCalcConfig,
    UnitRankConfig,
    Student,
    Apply,
    ApplyStatus,
    ConfirmLevel,
    Revision,
    DyfScore,
    CourseScore,
    FinalGrade,
    AuditLog,
    AuditRole,
    DyfFile,
    DyfFileType,
    CryptoProvider,
    RsaKeyGenOptions,
    AesGcmEncryptResult,
    EncryptPayloadOptions,
    DecryptDyfFileOptions,
    DecryptResult,
    CalcEngine,
    ScoreDetail,
    DyfTotalConfig,
    RankInput,
    RankResult,
    RankOptions,
    ApplyState,
    BatchState,
    FinalState,
    StudentInput,
    StudentValidationOptions,
    ImportDecision,
    ExistingStudent,
    ImportCheckInput,
    ImportCheckResult,
    ApplyPayload,
    ApplyValidationOptions,
} from './index'

// 引用所有类型，消除 noUnusedLocals 的"未使用 import"警告，同时编译期验证类型存在
export type _ApiSurfaceCheck = [
    Jwk,
    RsaAlgorithm,
    AesAlgorithm,
    EpochMs,
    ValidationResult,
    Batch,
    BatchStatus,
    CalcMode,
    RankScope,
    CalcConfig,
    UnitConfig,
    UnitConfigStatus,
    UnitType,
    UnitBinding,
    CascaderNode,
    ClassCascader,
    StudentField,
    ScoreType,
    ScoreTypeStepper,
    ScoreTypeRadio,
    ScoreTypeInput,
    Support,
    DyfConfig,
    DyfCategory,
    DyfGroup,
    DyfItem,
    UnitCalcConfig,
    UnitRankConfig,
    Student,
    Apply,
    ApplyStatus,
    ConfirmLevel,
    Revision,
    DyfScore,
    CourseScore,
    FinalGrade,
    AuditLog,
    AuditRole,
    DyfFile,
    DyfFileType,
    CryptoProvider,
    RsaKeyGenOptions,
    AesGcmEncryptResult,
    EncryptPayloadOptions,
    DecryptDyfFileOptions,
    DecryptResult,
    CalcEngine,
    ScoreDetail,
    DyfTotalConfig,
    RankInput,
    RankResult,
    RankOptions,
    ApplyState,
    BatchState,
    FinalState,
    StudentInput,
    StudentValidationOptions,
    ImportDecision,
    ExistingStudent,
    ImportCheckInput,
    ImportCheckResult,
    ApplyPayload,
    ApplyValidationOptions,
]

// 文档 docs/API.md 中提到的运行时值导出，逐一验证存在
describe('API 完整性（docs/API.md 对照）', () => {
    it('crypto 值导出', () => {
        for (const name of [
            'setCryptoProvider',
            'getCryptoProvider',
            'webCryptoProvider',
            'useWebCryptoProvider',
            'bytesToBase64',
            'base64ToBytes',
            'utf8ToBytes',
            'bytesToUtf8',
            'bytesToHex',
            'sha256Bytes',
            'sha256Hex',
            'DEFAULT_RSA_ALGORITHM',
            'generateRsaKeyPair',
            'importRsaPublicKey',
            'importRsaPrivateKey',
            'rsaEncrypt',
            'rsaDecrypt',
            'verifyRsaKeyPair',
            'DEFAULT_AES_ALGORITHM',
            'aesGcmEncrypt',
            'aesGcmDecrypt',
            'DYF_SCHEMA_VERSION',
            'encryptPayload',
            'decryptDyfFile',
        ]) {
            expect(name in shared, `缺少导出：${name}`).toBe(true)
        }
    })

    it('calc 值导出', () => {
        for (const name of [
            'calcDyfTotal',
            'resolveDyfTotalConfig',
            'extractDyfTotalConfig',
            'calcRank',
            'WeightedCalc',
            'FormulaCalc',
        ]) {
            expect(name in shared, `缺少导出：${name}`).toBe(true)
        }
    })

    it('state 值导出', () => {
        for (const name of [
            'APPLY_STATES',
            'APPLY_TRANSITIONS',
            'canApplyTransition',
            'assertApplyTransition',
            'nextApplyStates',
            'isApplyState',
            'BATCH_STATES',
            'BATCH_TRANSITIONS',
            'canBatchTransition',
            'assertBatchTransition',
            'nextBatchStates',
            'isBatchState',
            'FINAL_STATES',
            'FINAL_TRANSITIONS',
            'canFinalTransition',
            'assertFinalTransition',
            'nextFinalStates',
            'isFinalState',
        ]) {
            expect(name in shared, `缺少导出：${name}`).toBe(true)
        }
    })

    it('validate 值导出', () => {
        for (const name of [
            'validateStudentId',
            'validateStudentName',
            'validateStudent',
            'checkImport',
            'validateApplyPayload',
        ]) {
            expect(name in shared, `缺少导出：${name}`).toBe(true)
        }
    })
})